### ISSUE TITLE
v15-mc+0-mc-59998: Crash with forge

### ISSUE THREAD

**Issue by nak5124** [ameisen/jdk-mc#7]
Game crashes when pressing F3 key.
Minecraft version: 1.16.4 forge 35.1.4
Mod: Optifine 1.16.4 HD U G5

here is crash report.
https://gist.github.com/nak5124/65887e9a8ec3f0caff4bb676eada4b51

Without optifine, game crashes on launching game.
Error message is different from when optifine is enabled.

here is crash report.
https://gist.github.com/nak5124/c5e6573ce2a29d74067015e93799f96c

Without forge (i.e. vanilla), no error occurs.

15-release+0-mc-59994 has no problem.

**Comment by ameisen** [comment]
I encountered this as well on that version of forge.

Oddly enough, it works on `35.1.7` for me.

`'double java.lang.Math.IEEEremainder(double, double)'`

This is likely due to my floating point override changes. That should have been unchanged, though.

**Comment by ameisen** [comment]
I have this fixed locally and will mark it as fixed on the next commit.

**Comment by ameisen** [comment]
This is fixed in commit [0dcce38](https://github.com/ameisen/jdk-mc/commit/0dcce3836f1eb6fb3546339da1b20cb352992a3e), and [release 60001](https://github.com/ameisen/jdk-mc/releases/tag/v15-mc%2B0-mc-60001) includes the fix (it was actually fixed and then updated again).
