### ISSUE TITLE
v15-mc+0-mc-59998: Pressing F3 for debug screen crashes the game

### ISSUE THREAD

**Issue by tiberiusteng** [ameisen/jdk-mc#8]
Minecraft 1.16.3, Forge 34.1.25, Optifine 1.16.3 HD U G4

crash report:
https://gist.github.com/tiberiusteng/707ae17584c2339bb08a142d89495a17

**Comment by toinouH** [comment]
@tiberiusteng Could you replicate this bug on a vanilla client ?

**Comment by tiberiusteng** [comment]
@toinouH Vanilla 1.16.4 does not crash on pressing F3.
I was using the 15-release+0-mc-59994 build and it wouldn't crash on pressing F3 with the same modded installation.

**Comment by ameisen** [comment]
This is fixed in commit [0dcce38](https://github.com/ameisen/jdk-mc/commit/0dcce3836f1eb6fb3546339da1b20cb352992a3e), and [release 60001](https://github.com/ameisen/jdk-mc/releases/tag/v15-mc%2B0-mc-60001) includes the fix (it was actually fixed and then updated again).
